# Execute (bcs error load custom env file)-> docker compose --env-file .env.db up -d

version: '3.9'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - nest-guard-postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - nest-guard

  pgadmin:
    user: root
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - nest-guard-postgres-data:/var/lib/pgadmin
    env_file:
      - .env.db
    depends_on:
      - db
    networks:
      - nest-guard

  cache:
    image: redis:latest
    env_file:
      - .env.db
    ports:
      - "6379:6379"
    networks:
      - nest-guard

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - cache
    networks:
      - nest-guard

volumes:
  nest-guard-postgres-data:

networks:
  nest-guard: